preprocess:
  input: data/raw/clients.xls
  output: data/processed/data.csv
  
train:
  input: data/processed/data.csv
  baseline_path: model/baseline.pkl
  boosting_path: model/boosting.pkl
  output_X: data/test/X_test.csv
  output_y: data/test/y_test.csv


test:
  X_test: data/test/X_test.csv
  y_test: data/test/y_test.csv
  metrics_path: metrics/metrics.json
  baseline_path: model/baseline.pkl
  boosting_path: model/boosting.pkl